name: flutter_pdf_reader_app
description: A PDF viewing application similar to Google Drive.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.3
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true